name: CI with SonarCloud Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Baixar o código
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para o SonarCloud

      # Passo 2: Configurar Node.js (para projetos JavaScript)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Passo 3: Instalar dependências e rodar testes (se aplicável)
      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: npm test # Substitua pelo comando que gera relatório de cobertura (ex: "npm test -- --coverage")

      # Passo 4: Executar análise no SonarCloud
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token automático do GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token que você criou no Passo 1
